### ISSUE TITLE
Only works on .js files?

### ISSUE THREAD

**Issue by rodrigograca31** [vinliao/fast-arrow#2]
Im trying to use it on a `.jsx` file and nothing....

How would I go about allowing it to work on those files?

Thanks.

**Comment by SharpSeeEr** [comment]
Agreed - please add `.jsx` file support.  ~Better yet - put the supported extensions into the settings, allowing the user to add additional extensions.~ Edit: I can see how that could be difficult, since the language and path to snippets is defined in `package.json`.

P.S. Great work on this extension!  I've been needing this for a very long time.

**Comment by rodrigograca31** [comment]
Yeah that can be hard for the creator to implement but there's also `.tsx` (jsx but with typescript) so........

**Comment by rodrigograca31** [comment]
@SharpSeeEr since you mentioned that file, I had a look and found how to make it work! 
Will send a PR in a minute.
